  [[redirects]]
  from = "/*"
  to = "/assets/html/index.html"
  status = 200

[[redirects]]
  from = "/style.css"
  to = "/assets/css/style.css"
  status = 200

[[redirects]]
  from = "/script.js"
  to = "/assets/js/script.js"
  status = 200

# Redirect all other paths to index.html

