[[redirects]]
  from = "/about_page.css"
  to = "/assets/css/about_page.css"
  status = 200

[[redirects]]
  from = "/script.js"
  to = "/assets/js/script.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/assets/html/index.html"
  status = 200
